### ISSUE TITLE
Change how URLs are created

### ISSUE THREAD

**Issue by ARawles** [ARawles/BMRSr#16]
Rather than relying on `paste0` calls, the URLs should be built using `httr` as a URL object

**Comment by jimrothstein** [comment]
from @ARawles 
1. The URLs created by the `build_` functions currently just paste the arguments together to make the URL like this
```if (!is.null(week)){
request$url = paste0(request$url, "&Week=", week)
}
```
But it would probably be more efficient (and much easier to test) if the URLs were constructed using the `httr::build_url` and `httr::modify_url` functions. This way, all of the non-null arguments passed when the function is called can be added to the `query` attribute of the created URL and we could take the number of lines in the function down from the tens to maybe 5 or 6. I'm imaging it looking something like this:
```
bmrs_url <- httr::modify_url(url, query = list(input_params))
```
The only potential downside is that the URL that's currently returned has a few extra attributes (`service_type`, `data_item`), so these would still need to be added to the URL object if it's created by the `build_url()` function.

**Comment by jimrothstein** [comment]
Hi:
I've forked your repo, gotten an account and APIKey from the company.    But something isn't right:
In Browser, I get 403 invalid API.
In R, with httr:: I get status 200,  but no data.
Anything stand out?
https://api.bmreports.com/BMRS/B1720/v1?APIKey=1234567&settlement_date=2020-10-10

**Comment by ARawles** [comment]
A couple of things spring to mind:
I know that the API will sometimes return a 200 code but with the error actually embedded within the response. This is why in the browser you see the error message but in R it looks like everything worked - if you use `httr::content()` to inspect the content of the response, you should see something that resembles what you see in the browser.
Also, just to double check, the API key you that you will have will need to replace the `APIKey` part of the URL - the `123467` is just in there as a filler.
And then I know that the B1720 data item also needs a `Period` parameter specified in the URL. You can use `Period=*` to get data for all Settlement Periods or when using the `build_url` function, you can use `period = "*"`.
Then even if you put all that together, it looks as though that data item doesn't have any data for that Settlement Date, so I'd try one from maybe the start of the year.

**Comment by jimrothstein** [comment]
"https://api.bmreports.com/BMRS/B1720/v1?APIKey=4rs1u6b3ror2wjg&Period=*&SettlementDate=2020-10-10" 

Now I get 204 - no content.
Are my cases correct;   "Period" or "period" ?

I used "scripting_key"  on my profile as the APIKey.

I'm try to follow this guide (July 2020)   Section 5.1.1
https://www.elexon.co.uk/documents/training-guidance/bsc-guidance-notes/bmrs-api-and-data-push-user-guide-2/

**Comment by jimrothstein** [comment]
This where I am trying to get to (works for Google API),  I'm open to other ways.
```
# Google calls main URL  "endpoint"
endpoint  <- paste0("https://api.bmreports.com/BMRS/B1720/v1")

# set list with parameters
params  <- list( API_key= api_key,
                Period=1,
                ServiceType="csv",
                settlement_date= settlement_date)

# and the GET
res <-   httr::GET(endpoint, query=params)

So it same structure over and over again - for each endpoint.
```

**Comment by ARawles** [comment]
Your cases are correct, there's just no data for that date - 2019-10-13 definitely has data if you want to try that.

That approach looks okay, but I'd focus more on editing the code in the `build()` functions rather than starting from scratch as the `GET`ting is performed by separate set of functions.

**Comment by jimrothstein** [comment]
Works!   Thanks.

Next:  will proceed with build() functions.    (Today is election day in US, so I'll pick this in another day or so.)

**Comment by jimrothstein** [comment]
* Below is quick & dirty, using `modify_url `in 2 places.
* Good ideas in this vignette : https://httr.r-lib.org/articles/api-packages.html
* Will clean it up if looks like direction you hoping for.

```
# GOAL:
# "https://api.bmreports.com/BMRS/B1720/v1?APIKey=4rs1u6b3ror2wjg&Period=*&SettlementDate=2019-10-13"
#
  data_item  <- "B1720"
  api_version  <- "v1" 
  SettlementDate  <-  "2019-10-13"
  Period="*"

base_url <- "https://api.bmreports.com/"
the_url <- httr::modify_url(base_url, 
                    path= paste0("BMRS/", data_item,"/", api_version))**

the_url   # "https://api.bmreports.com/BMRS/B1720/v1"


query= list( APIKey= api_key, 
                       Period=Period, 
                       ServiceType= "csv",
                       SettlementDate=SettlementDate)

unlist(query)
the_url <- httr::modify_url(the_url, query=query)


res  <- httr::GET(the_url)
```

**Comment by ARawles** [comment]
Yep, looking good to me.

Only thought is that you don't need to bother with the `GET` step at the bottom because that's handled outside of the `build` functions but other than that looks good!

Happy for you to turn this into a PR after a bit of a cleanup.

**Comment by jimrothstein** [comment]
Thx for quick feedback.   Will clean, use same names you used.  Will do tomorrow.
Also, some of your code lines are a bit long.   What are your thoughts about using this approach (when many arguments, long lines)

ie separate lines, thought it looks terrible here
```
f <- function( 
                      x = NULL,

                      y = NULL,

                      z  = NULL

)
```

See https://style.tidyverse.org/functions.html#long-lines-1

**Comment by ARawles** [comment]
Happy for long lines to be split at commas (that's actually the style I use now if not at the time), but no need for the space between lines I don't think

**Comment by jimrothstein** [comment]
Will finish up over weekend ... Read some of R code `modify_url` (see `url.R` in httr pkg) and it is not very well documented.  Maybe this is standard HTTP stuff; it follows the standard https://tools.ietf.org/html/rfc3986 , which is readable and helped clarify couple of variables for me.

**Comment by ARawles** [comment]
Good progress has been made for the `build_b_call()` in dc6ea80d278f5c10b360f0766104383d64508b52. This just needs to be replicated in the other build functions now.

**Comment by ARawles** [comment]
Replicated in the other functions.
