### ISSUE TITLE
checking parameters

### ISSUE THREAD

**Issue by jimrothstein** [ARawles/BMRSr#18]
@ARawles 
Just a thought ...

NOW:   Inside each function,  each parameter is checked one-by-one for being NULL or properly formatted.

Any thoughts on using `switch` or `dplyr::case_when()`  to make the code a little cleaner?

Thx.

**Comment by ARawles** [comment]
I agree that it's a bit overkill at the moment. Check the latest commit (8abbe8b4ff2cb20756554422b9c0eb9237813e44) for a potential new method of checking.

I think that actually this can be abstracted even further with a master list of parameters and their required "cleaning" functions. That way, you can just pass everything that's been provided in the `build()` call to a function that will look up what needs to be done to the parameter before it's assigned, do it and then return it. That way, you won't need to have a separate line for each parameter, it'll be more like 
```
input_params <- fix_parameters(args)
```

**Comment by jimrothstein** [comment]
This is very nice:
`fix_parameter <- function(param, before = NULL, ...)`

Do you want me to work on the plural form, ie list of all parameters and "cleaning" functions?
`input_params <- fix_parameters(args)`

NOTE:   might be useful, captures a list with the param name and value ONLY if included in the call.

`
g  <- function(x, ...) {

  rlang::enexprs( ... )
}

x  <- "test"

g(x, b="hello")

g(x, a="hello", b="hi", c="good day", d="good evening")
`

**Comment by ARawles** [comment]
If you could work on the plural form, that would be fantastic. If you look in the data-raw folder, you'll see some examples of where I've used lists to save data pairings elsewhere.

What I'm envisioning is a list that looks something like:
```
list(
    settlement_date = format_date,
    ...
)
```
Which is basically just the function parameter as the name and then the function that needs to be used to clean it up as the value. That way, the `fix_parameters` function can just use that master list for all of the provided parameters.

Using `enexprs` to capture the arguments provided seems like a sensible approach for the `fix_parameters()` function.

**Comment by jimrothstein** [comment]
Will do ... your list structure looks like right way.
Need a couple days, but will get back to soon.

**Comment by jimrothstein** [comment]
Just want to check a few assumptions with you:

* each param has one `before` function  (or NULL)
* for each param, the `before` function depends ONLY on this param (and NOT any other variables),   HOWEVER
in `do.call` you have possibility of more than one:   args=list(param, __`...`__)

@ARawles

**Comment by ARawles** [comment]
That's correct

**Comment by jimrothstein** [comment]
@ARawles 
Took me awhile to figure this out.  Here's one method.   Now adding to my branch and PR (tomorrow).

```# fake data
raw_params  <- list(pm1 = "A", pm2 ="B" , pm3 ="C")

#   GOAL:     input_params:   list (pm1 = "1A", pm2 = "2B", pm3 = "3C")

##  IDEA is to pick correct fix_function based on param's name.
## Then apply the function to param's value.
## Repeat for all the parameters.

# helps to separate into two vectors, param names & values
names(raw_params )  # char
values  <- unlist(raw_params)  
values


# match each param to fix function
fix_funs  <-  list( pm1 = function(x) paste0("1",x),
                    pm2 = function(x) paste0("2",x),
                    pm3 = function(x) paste0("3",x)
                    )
fix_funs


# given param, return its fix function
pick_function  <- function(name = x) {
  fix_funs[[name]]
}


# TWO-steps, get right fix function (based on param name), then apply to value 
input_params  <- map2(values, names(raw_params),
                     ~ pick_function(.y)(.x)) 
# matches GOAL
input_params
```

**Comment by ARawles** [comment]
That's a great base @jimrothstein so thank you for that. I've used what you've done and implemented automatic checking/cleaning for the three `build` functions in the latest commit (8d91862046ba1c4990f83bf788beca4ee44c5f76) if you want to take a look.

Pretty happy with it for now so I'm going to close this.

**Comment by jimrothstein** [comment]
@ARawles  
You are a lot quicker than I.    Looks like you used clever, concise code .... reading it now.
